import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const pixelifySansBold = localFont({
  src: "./fonts/PixelifySans-Bold.ttf",
  variable: "--font-pixelifySans-bold",
  weight: "100 900",
});

const pixelifySansMedium = localFont({
  src: "./fonts/PixelifySans-Medium.ttf",
  variable: "--font-pixelifySans-medium",
  weight: "100 900",
});

const pixelifySansRegular = localFont({
  src: "./fonts/PixelifySans-Regular.ttf",
  variable: "--font-pixelifySans-regular",
  weight: "100 900",
});
const pixelifySansSemiBold = localFont({
  src: "./fonts/PixelifySans-SemiBold.ttf",
  variable: "--font-pixelifySans-semibold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}
        ${pixelifySansBold.variable}
        ${pixelifySansMedium.variable}
        ${pixelifySansRegular.variable}
        ${pixelifySansSemiBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
